### ISSUE TITLE
Not working at all in VS 2015

### ISSUE THREAD

**Issue by tobiasmayr** [rxcompile/UE4Intellisense#2]
Hi,
I just installed this plugin in Visual Studio 2015, but when I hit Ctrl+space to get intellisense suggestions inside one of the supported macros, no suggestions show up.
I am using Unreal Engine 4.12.5 if that matters.

**Comment by rxcompile** [comment]
@tobiasmayr Please post code sample and point to location where suggestions does not shown.
By the way, Intellisense dont work with Resharper C++ or Visual Assist X (this products use their own engines to show auto-completion list). Sorry, no plans for make plugins for VAX or ReSharper.

**Comment by tobiasmayr** [comment]
Oh that's bad that it doesn't work with ReSharper :(
But I thought I had tried it out without too, and it didn't work. Now that I tried it again with ReSharper disabled, it worked.

So, sorry for the false alarm :)
Thanks!
