### ISSUE TITLE
Compile for Visual Studio 2017

### ISSUE THREAD

**Issue by stevefan1999-personal** [rxcompile/UE4Intellisense#5]
Only VS2015 can install this plugin according to the marketplace, what should I do to get it working on VS2017?

**Comment by rxcompile** [comment]
Thanks for your interest in this extension. [https://github.com/rxcompile/UE4Intellisense/issues/3](https://github.com/rxcompile/UE4Intellisense/issues/3) explains it all about VS2017 support.

tl;dr; use build from [https://github.com/rxcompile/UE4Intellisense/releases/latest](https://github.com/rxcompile/UE4Intellisense/releases/latest)

I save this issue in open state, so anyone can see it.
